package herdrsock

const (
	MethodPing                       = "ping"
	MethodServerStop                 = "server.stop"
	MethodServerLiveHandoff          = "server.live_handoff"
	MethodServerReloadConfig         = "server.reload_config"
	MethodServerAgentManifests       = "server.agent_manifests"
	MethodServerReloadAgentManifests = "server.reload_agent_manifests"

	MethodNotificationShow       = "notification.show"
	MethodClientWindowTitleSet   = "client.window_title.set"
	MethodClientWindowTitleClear = "client.window_title.clear"

	MethodWorkspaceCreate = "workspace.create"
	MethodWorkspaceList   = "workspace.list"
	MethodWorkspaceGet    = "workspace.get"
	MethodWorkspaceFocus  = "workspace.focus"
	MethodWorkspaceRename = "workspace.rename"
	MethodWorkspaceClose  = "workspace.close"

	MethodWorktreeList   = "worktree.list"
	MethodWorktreeCreate = "worktree.create"
	MethodWorktreeOpen   = "worktree.open"
	MethodWorktreeRemove = "worktree.remove"

	MethodTabCreate = "tab.create"
	MethodTabList   = "tab.list"
	MethodTabGet    = "tab.get"
	MethodTabFocus  = "tab.focus"
	MethodTabRename = "tab.rename"
	MethodTabClose  = "tab.close"

	MethodPaneSplit               = "pane.split"
	MethodPaneSwap                = "pane.swap"
	MethodPaneMove                = "pane.move"
	MethodPaneZoom                = "pane.zoom"
	MethodPaneLayout              = "pane.layout"
	MethodPaneProcessInfo         = "pane.process_info"
	MethodPaneNeighbor            = "pane.neighbor"
	MethodPaneEdges               = "pane.edges"
	MethodPaneFocusDirection      = "pane.focus_direction"
	MethodPaneResize              = "pane.resize"
	MethodPaneList                = "pane.list"
	MethodPaneCurrent             = "pane.current"
	MethodPaneGet                 = "pane.get"
	MethodPaneRename              = "pane.rename"
	MethodPaneSendText            = "pane.send_text"
	MethodPaneSendKeys            = "pane.send_keys"
	MethodPaneSendInput           = "pane.send_input"
	MethodPaneRead                = "pane.read"
	MethodPaneReportAgent         = "pane.report_agent"
	MethodPaneReportAgentSession  = "pane.report_agent_session"
	MethodPaneReportMetadata      = "pane.report_metadata"
	MethodPaneClearAgentAuthority = "pane.clear_agent_authority"
	MethodPaneReleaseAgent        = "pane.release_agent"
	MethodPaneClose               = "pane.close"
	MethodPaneWaitForOutput       = "pane.wait_for_output"

	MethodLayoutExport = "layout.export"
	MethodLayoutApply  = "layout.apply"

	MethodAgentList    = "agent.list"
	MethodAgentGet     = "agent.get"
	MethodAgentRead    = "agent.read"
	MethodAgentExplain = "agent.explain"
	MethodAgentSend    = "agent.send"
	MethodAgentRename  = "agent.rename"
	MethodAgentFocus   = "agent.focus"
	MethodAgentStart   = "agent.start"

	MethodEventsSubscribe = "events.subscribe"
	MethodEventsWait      = "events.wait"

	MethodIntegrationInstall   = "integration.install"
	MethodIntegrationUninstall = "integration.uninstall"

	MethodPluginLink         = "plugin.link"
	MethodPluginList         = "plugin.list"
	MethodPluginUnlink       = "plugin.unlink"
	MethodPluginEnable       = "plugin.enable"
	MethodPluginDisable      = "plugin.disable"
	MethodPluginActionList   = "plugin.action.list"
	MethodPluginActionInvoke = "plugin.action.invoke"
	MethodPluginLogList      = "plugin.log.list"
	MethodPluginPaneOpen     = "plugin.pane.open"
	MethodPluginPaneFocus    = "plugin.pane.focus"
	MethodPluginPaneClose    = "plugin.pane.close"
)
